# Generated by Django 5.0.6 on 2024-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw2app', '0002_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path_to_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
